/*
 * GhostCord, a desktop app aiming to give you a snappier Discord Experience
 * Copyright (c) 2023 Vendicated and GhostCord contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import "./themedSplash";
import "./ipcCommands";
import "./appBadge";
import "./fixes";
import "./arrpc";
import "__patches__"; // auto generated by the build script

export * as Components from "./components";

import SettingsUi from "./components/settings/Settings";
import { GhostCordLogger } from "./logger";
import { Settings } from "./settings";
export { Settings };

import type SettingsPlugin from "@vencord/types/plugins/_core/settings";

GhostCordLogger.log("read if cute :3");
GhostCordLogger.log("DriizzyyB v" + GhostCordNative.app.getVersion());

const customSettingsSections = (GhostCord.Plugins.plugins.Settings as any as typeof SettingsPlugin).customSections;

customSettingsSections.push(() => ({
    section: "DriizzyyB",
    label: "DriizzyyB Settings",
    element: SettingsUi,
    className: "vc-DriizzyyB-settings"
}));
